---
title: "시각화"
author: "2018580008 문혜현"
date: "`r format(Sys.Date())`"
output: 
  html_document:
    fig_height: 7
    fig_width: 7
    highlight: textmate
    theme: cosmo
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.align = "center", message=F, warning=F)
```


# 라이브러리 설치

```{r}
if(!require(readxl)){install.packages("readxl"); library(readxl)}
if(!require(stringr)){install.packages("stringr"); library(stringr)}
if(!require(dplyr)){install.packages("dplyr"); library(dplyr)}
if(!require(reshape2)){install.packages("reshape2"); library(reshape2)}
if(!require(ggplot2)){install.packages("ggplot2"); library(ggplot2)}
if(!require(plotly)){install.packages("plotly"); library(plotly)}
if(!require(scales)){install.packages("scales"); library(scales)}
if(!require(patchwork)){
        if(!require(devtools)){install.packages("devtools")}
        devtools::install_github("thomasp85/patchwork"); library(plotly)
}

if(!require(lubridate)){install.packages("lubridate"); library(lubridate)}
if(!require(car)){install.packages("car"); library(car)}
if(!require(nortest)){install.packages("nortest"); library(nortest)}
if(!require(tseries)){install.packages("tseries"); library(tseries)}
if(!require(gridExtra)){install.packages("gridExtra"); library(gridExtra)}
if(!require(colorspace)){install.packages("colorspace");   library(colorspace)}
```

```{r}

if(!require(packcircles)){install.packages("packcircles"); library(packcircles)}
if(!require(viridis)){install.packages("viridis"); library(viridis)}

if(!require(pheatmap)){install.packages("pheatmap");   library(pheatmap)}
if(!require(grid)){install.packages("grid"); library(grid)}

if(!require(BiocManager)){install.packages("BiocManager");   library(BiocManager)}
if(!require(ComplexHeatmap)){install.packages("ComplexHeatmap");   library(ComplexHeatmap)}
if(!require(circlize)){install.packages("circlize");   library(circlize)}


```


## 전처리

```{r}
setwd("C:\\Users\\moonf\\Desktop\\2020.2학기\\빅데이터경진대회\\데이터")

#막대그래프용
load("시간대별어린이(12세이하)교통사고.rdata")
load("요일별어린이(12세이하)교통사고.rdata")
load("시간대별스쿨존내어린이(12세이하)교통사고.rdata")
load("요일별스쿨존내어린이(12세이하)교통사고.rdata")

#버블plot용
load("법규위반별스쿨존내어린이(12세이하)교통사고.rdata")

#Circular plot용
load("월별어린이(12세이하)교통사고.RData")
load("월별스쿨존내어린이(12세이하)교통사고.RData")
```



# 시각화 준비

```{r}
theme_basic2<-theme(   legend.position = "none",
          axis.ticks.y = element_blank(),
          axis.line.y = element_blank(),
          axis.title.y=element_blank(),
        axis.line.x=element_blank(),
          axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text=element_text(family="mono",size=15,face="bold")
)
```



## 5개년 전국의 스쿨존/비스쿨존 시간별 사고건수(heatmap)
image 추출 : 350*320
```{r}
# 시각화 전처리
time_acc<-time_trf %>% group_by(시간) %>% summarize(sum_acc=sum(사고건수))
time_acc<-as.data.frame(time_acc)

time_s_acc<-time_s_trf %>% group_by(시간) %>% summarize(sum_acc=sum(사고건수))
time_s_acc<-as.data.frame(time_s_acc)

time_nos_acc<-time_acc
time_nos_acc$sum_acc<-time_acc$sum_acc-time_s_acc$sum_acc
time_final<-merge(time_s_acc, time_nos_acc, by="시간")
colnames(time_final)<-c("시간","스쿨존","비스쿨존")
time_final$스쿨존<-(time_final$스쿨존-mean(time_final$스쿨존))/sd(time_final$스쿨존)
time_final$비스쿨존<-(time_final$비스쿨존-mean(time_final$비스쿨존))/sd(time_final$비스쿨존)

```

```{r}

# ggplot2
time_final_g<-melt(time_final,id=c("시간"))
time_final_g<-as.data.frame(time_final_g)
colnames(time_final_g)<-c("시간","유형","사고건수")
time_final_g$유형<-as.factor(time_final_g$유형)
time_final_g$변경유형<-rep("변경유형",nrow(time_final_g))

# 라벨 보기 좋게 수정
time_final_g$시간[time_final_g$시간=="0시~2시"]="00~02시"
time_final_g$시간[time_final_g$시간=="2시~4시"]="02~04시"
time_final_g$시간[time_final_g$시간=="4시~6시"]="04~06시"
time_final_g$시간[time_final_g$시간=="6시~8시"]="06~08시"
time_final_g$시간[time_final_g$시간=="8시~10시"]="08~10시"
time_final_g$시간[time_final_g$시간=="10시~12시"]="10~12시"
time_final_g$시간[time_final_g$시간=="12시~14시"]="12~14시"
time_final_g$시간[time_final_g$시간=="14시~16시"]="14~16시"
time_final_g$시간[time_final_g$시간=="16시~18시"]="16~18시"
time_final_g$시간[time_final_g$시간=="18시~20시"]="18~20시"
time_final_g$시간[time_final_g$시간=="20시~22시"]="20~22시"
time_final_g$시간[time_final_g$시간=="22시~24시"]="22~24시"


ggplot(time_final_g)+geom_raster(aes(x=변경유형,y=시간,fill=사고건수))+
  facet_grid(. ~ 유형)+
  scale_fill_gradient(low="#fef0d9",high="#dc301f")+
  scale_y_discrete(limits=c("22~24시","20~22시","18~20시","16~18시","14~16시","12~14시","10~12시","08~10시","06~08시","04~06시","02~04시","00~02시"))+
  theme(plot.background = element_rect(fill = "#222A35"),
        panel.background = element_rect(fill = "#222A35"),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_text(size = 14,face='bold',colour='white'),
        axis.text.y = element_text(size = 12,face='bold',color='white'),
        axis.text.x =element_blank())


```


## 5개년 전국의 스클존/비스쿨존 요일별 사고건수(heatmap)
image 추출 : 330*310

```{r}
# 시각화 전처리
week_acc<-week_trf %>% group_by(요일) %>% summarize(sum_acc=sum(사고건수))
week_acc<-as.data.frame(week_acc)

week_s_acc<-week_s_trf %>% group_by(요일) %>% summarize(sum_acc=sum(사고건수))
week_s_acc<-as.data.frame(week_s_acc)

week_nos_acc<-week_acc
week_nos_acc$sum_acc<-week_acc$sum_acc-week_s_acc$sum_acc
week_final<-merge(week_s_acc, week_nos_acc, by="요일")
colnames(week_final)<-c("요일","스쿨존","비스쿨존")
week_final$스쿨존<-(week_final$스쿨존-mean(week_final$스쿨존))/sd(week_final$스쿨존)
week_final$비스쿨존<-(week_final$비스쿨존-mean(week_final$비스쿨존))/sd(week_final$비스쿨존)

```


```{r}
# ggplot2
week_final_g<-melt(week_final,id=c("요일"))
week_final_g<-as.data.frame(week_final_g)
colnames(week_final_g)<-c("요일","유형","사고건수")
week_final_g$유형<-as.factor(week_final_g$유형)
week_final_g$변경유형<-rep("변경유형",nrow(week_final_g))

ggplot(week_final_g)+geom_raster(aes(x=변경유형,y=요일,fill=사고건수))+
  facet_grid(. ~ 유형)+
  scale_fill_gradient(low="#fef0d9",high="#dc301f")+
  scale_y_discrete(limits=c("일","토","금","목","수","화","월"))+
  theme(plot.background = element_rect(fill = "#222A35"),
        panel.background = element_rect(fill = "#222A35"),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_text(size = 13,face='bold',colour='white'),
        axis.text.y = element_text(size = 13,face='bold',color='white'),
        axis.text.x =element_blank())

```


## 5개년 전국의 스쿨존내 법규위반별 사고건수(circle packaged plot)
image 추출 : ppt 크기에 맞추어 결과창 바꾸고 캡처하기


```{r}
## 시각화 전처리
law_acc<-law_trf %>% group_by(법규) %>% summarize(sum_acc=sum(사고건수))
law_acc<-as.data.frame(law_acc)

# 시각화를 위한 데이터생성
packing <- circleProgressiveLayout(law_acc$sum_acc, sizetype='area')
law_acc <- cbind(law_acc, packing)
dat.gg <- circleLayoutVertices(packing, npoints=50)

# 옵션
circle_pack_theme<-theme(plot.background = element_rect(fill = "#222A35"),
                      panel.background = element_rect(fill = "#222A35"),
                      legend.position = "none",
                      panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
          axis.ticks.y = element_blank(),
          axis.line.y = element_blank(),
          axis.title.y=element_blank(),
          axis.text.y = element_blank(),
          
           axis.ticks.x = element_blank(),
        axis.line.x=element_blank(),
          axis.title.x = element_blank(),
        axis.text.x = element_blank()
)

```

```{r}
# 시각화
#my_colors <- sample(heat_hcl(nrow(law_acc),c=c(80,30),l=c(30,90),power=c(1/5,1.5)),12)
# RColorBrewer::brewer.pal(9, "Reds")
my_colors <-RColorBrewer::brewer.pal(9, "OrRd")
my_colors<-c(my_colors,my_colors[1:3])

ggplot() + 
  geom_polygon(data = dat.gg, aes(x, y, group = id, fill=as.factor(id)), colour = "#222A35") +
  scale_fill_manual(values = my_colors) +
  geom_text(data = law_acc, aes(x, y, size=sum_acc, label = 법규),col="black",fontface='bold') +
  scale_size_continuous(range = c(1,6))+ coord_equal() +circle_pack_theme
 


```


# 년도별 월별 
image 추출 : 800*770

## 수정 후(3)_정규화


```{r}
#Circular plot용
month_trf<-month_trf[,1:3]
month_s_trf<-month_s_trf[,1:3]
month_nos_trf<-data.frame(기준년도=month_trf$기준년도,월= month_trf$월, 사고건수=month_trf$사고건수-month_s_trf$사고건수)

month_s_trf$ym<-paste(month_s_trf$기준년도,month_s_trf$월)
month_s_trf_ym<-month_s_trf[,c('ym','사고건수')]

month_nos_trf$ym<-paste(month_nos_trf$기준년도,month_nos_trf$월)
month_nos_trf_ym<-month_nos_trf[,c('ym','사고건수')]

```

```{r}
month_s_trf<-month_s_trf[,3:4]
colnames(month_s_trf)<-c("스쿨존","ym")
month_nos_trf<-month_nos_trf[,3:4]
colnames(month_nos_trf)<-c("비스쿨존","ym")

month_s_trf$스쿨존<-(month_s_trf$스쿨존-mean(month_s_trf$스쿨존))/sd(month_s_trf$스쿨존)+5
month_nos_trf$비스쿨존<-(month_nos_trf$비스쿨존-mean(month_nos_trf$비스쿨존))/sd(month_nos_trf$비스쿨존)+5

month_final<-merge(month_s_trf, month_nos_trf, by='ym')
month_final<-melt(month_final, id='ym')

colnames(month_final)<-c("ym","유형","사고건수")

month_rev<-c(1:which.min(month_final$유형=="스쿨존")-1, nrow(month_final):(which.min(month_final$유형=="스쿨존")))
month_final<-month_final[month_rev,]



```

```{r}
# library
library(tidyverse)

empty_bar <- 4
to_add <- data.frame( matrix(NA, empty_bar*nlevels(month_final$유형), ncol(month_final)) )
colnames(to_add) <- colnames(month_final)
to_add$유형 <- rep(levels(month_final$유형), each=empty_bar)
month_final <- rbind(month_final, to_add)
month_final <- month_final %>% arrange(유형)
month_final$id <- seq(1, nrow(month_final))
 
# Get the name and the y position of each label
label_month_final <- month_final
number_of_bar <- nrow(label_month_final)
angle <- 90 - 360 * (label_month_final$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_month_final$hjust <- ifelse( angle < -90, 1, 0)
label_month_final$angle <- ifelse(angle < -90, angle+180, angle)

ym_which<-c(which(label_month_final$ym=="2015 01월"),
which(label_month_final$ym=="2016 01월"),
which(label_month_final$ym=="2017 01월"),
which(label_month_final$ym=="2018 01월"),
which(label_month_final$ym=="2019 01월"))
label_month_final$ym[-c(ym_which)]<-NA
label_month_final$사고건수[-c(ym_which)]<-NA

# prepare a data frame for base lines
base_data <- month_final %>% 
  group_by(유형) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))

# Make the plot
p <- ggplot(month_final, aes(x=as.factor(id), y=사고건수, fill=사고건수)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  geom_bar(stat="identity") +
  ylim(-5,10) +scale_fill_gradient(low="#fef0d9",high="#dc301f")  +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "#222A35"),
        panel.background = element_rect(fill = "#222A35"),
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  coord_polar()+
  geom_text(data=label_month_final, aes(x=id, y=6, label=ym, hjust=hjust), color="white",size=3.5, fontface='bold',angle= label_month_final$angle, inherit.aes = FALSE )+
  geom_text(data=base_data, aes(x = title, y = -3.5, label=유형), hjust=c(0,1), colour = "white", size=5, fontface="bold", inherit.aes = FALSE)
 

p
```


